# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-involves' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-involves
  pod 'TraktKit', '~> 1.1.1'

  target 'ios-involvesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-involvesUITests' do
    # Pods for testing
  end

end
